import * as pdfjsLib from 'pdfjs-dist';
import mammoth from 'mammoth';

// Use a hardcoded known-good version instead of dynamic
pdfjsLib.GlobalWorkerOptions.workerSrc = `https://cdn.jsdelivr.net/npm/pdfjs-dist@4.8.69/build/pdf.worker.min.js`;
export const analyzePDFHealth = async (pdf, fileSize) => {
    try {
        const metadata = await pdf.getMetadata();
        const numPages = pdf.numPages;
        const issues = [];
        const page = await pdf.getPage(1);
        const textContent = await page.getTextContent();
        const totalTextLength = textContent.items.map(i => i.str).join('').length;
        const isScanned = totalTextLength < 200 && fileSize > 200000;
        
        const creator = metadata?.info?.Creator ?? '';
        const producer = metadata?.info?.Producer ?? '';
        const isResumeBuilder = /Canva|Novoresume|Zety|Resume\.io|EnhanCV|CVMaker|Wix/i.test(creator + producer);
        
        if (numPages > 2) issues.push({ type: "page_count", severity: "low", message: `${numPages} pages detected`, fix: "Consider condensing to 2 pages" });
        if (isResumeBuilder) issues.push({ type: "resume_builder", severity: "medium", message: `Generated by ${creator || producer}`, fix: "Export as plain text or use Microsoft Word" });
        if (isScanned) issues.push({ type: "scanned_pdf", severity: "high", message: "No selectable text found - appears scanned", fix: "Use OCR or recreate as text-based PDF" });
        
        return { pageCount: numPages, issues, textLength: totalTextLength, fileSize };
    } catch (error) {
        return { pageCount: 0, issues: [], textLength: 0, fileSize: fileSize };
    }
};

export const parsePDF = async (file) => {
    return new Promise((resolve, reject) => {
        const reader = new FileReader();
        reader.onload = async function(e) {
            try {
                const typedarray = new Uint8Array(e.target.result);
                const pdf = await pdfjsLib.getDocument({ data: typedarray }).promise;
                let fullText = '';
                for (let i = 1; i <= pdf.numPages; i++) {
                    const page = await pdf.getPage(i);
                    const textContent = await page.getTextContent();
                    fullText += textContent.items.map(item => item.str).join(' ') + '\n';
                }
                resolve({ pdf, fullText });
            } catch (error) {
                reject(new Error('Failed to parse PDF: ' + error.message));
            }
        };
        reader.onerror = () => reject(new Error('Failed to read file'));
        reader.readAsArrayBuffer(file);
    });
};

export const extractDocx = async (file) => {
    return new Promise((resolve, reject) => {
        const reader = new FileReader();
        reader.onload = async function(e) {
            try {
                const result = await mammoth.extractRawText({ arrayBuffer: e.target.result });
                if (result.value && result.value.length > 50) resolve(result.value);
                else reject(new Error('Could not extract text from DOCX'));
            } catch (error) {
                reject(new Error('Failed to parse DOCX: ' + error.message));
            }
        };
        reader.onerror = () => reject(new Error('Failed to read file'));
        reader.readAsArrayBuffer(file);
    });
};